import { nanoid } from "nanoid";
import Logo from "./productt.png";

export const product = [
  {
    id: nanoid(),
    category: "Vegetable",
    name: "Calabrese Broccoli",
    originalPrice: "$20.00",
    currentPrice: "$13.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Fresh",
    name: "Fresh Banana Fruites",
    originalPrice: "$20.00",
    currentPrice: "$14.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Millets",
    name: "White Nuts",
    originalPrice: "$20.00",
    currentPrice: "$15.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Vegetable",
    name: "Vegan Red Tomato",
    originalPrice: "$20.00",
    currentPrice: "$17.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Health",
    name: "Mung Bean",
    originalPrice: "$20.00",
    currentPrice: "$11.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Nuts",
    name: "Brown Hazelnut",
    originalPrice: "$20.00",
    currentPrice: "$12.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Fresh",
    name: "Eggs",
    originalPrice: "$20.00",
    currentPrice: "$17.00",
    rating: "★★★★★",
    img: Logo,
  },
  {
    id: nanoid(),
    category: "Fresh",
    name: "Zelco Suji Elaichi Rusk",
    originalPrice: "$20.00",
    currentPrice: "$15.00",
    rating: "★★★★★",
    img: Logo,
  },
];
